import {
  Heart,
  Trophy,
  Flame,
  CheckCircle,
  Plus,
  X,
  Target,
  Award,
  User,
  Save,
  TrendingUp,
  Calendar,
  Star,
  Share2,
  Download,
  Upload,
  BarChart,
  Clock,
  Zap,
  Shield,
  BookOpen,
  Settings,
  ChevronRight,
  MessageCircle,
  Users,
  Bell,
  Send,
  UserPlus,
  Mail,
  Globe,
  Hash,
  Lock,
  Search,
  MoreVertical,
  Smile,
  Paperclip,
  ThumbsUp,
  Play,
  Pause,
  RotateCcw,
} from "lucide-react";

export const Icons = {
  Heart,
  Trophy,
  Flame,
  CheckCircle,
  Plus,
  X,
  Target,
  Award,
  User,
  Save,
  TrendingUp,
  Calendar,
  Star,
  Share2,
  Download,
  Upload,
  BarChart,
  Clock,
  Zap,
  Shield,
  BookOpen,
  Settings,
  ChevronRight,
  MessageCircle,
  Users,
  Bell,
  Send,
  UserPlus,
  Mail,
  Globe,
  Hash,
  Lock,
  Search,
  MoreVertical,
  Smile,
  Paperclip,
  ThumbsUp,
  Play,
  Pause,
  RotateCcw,
};

export const CONFIG = {
  fears: [
    "Peur de l'échec",
    "Peur du jugement",
    "Manque de confiance",
    "Procrastination",
    "Perfectionnisme",
  ],
  goals: [
    "Créer une entreprise",
    "Apprendre une compétence",
    "Améliorer sa forme physique",
    "Développer sa créativité",
  ],
  levels: {
    0: { name: "Novice", minPoints: 0 },
    1: { name: "Initié", minPoints: 100 },
    2: { name: "Engagé", minPoints: 300 },
  },
  challenges: {
    "Créer une entreprise": [
      {
        id: "c-bizplan",
        title: "Rédiger le Business Plan",
        points: 100,
        difficulty: "medium",
        subGoals: [
          "Définir les revenus",
          "Estimer les coûts",
          "Rédiger un résumé",
        ],
      },
    ],
    "Maîtriser la Procrastination": [
      {
        id: "c-quickwin",
        title: "Victoire Rapide",
        points: 30,
        difficulty: "easy",
        subGoals: [
          "Identifier une tâche de 5 min",
          "La faire maintenant",
          "Célébrer",
        ],
      },
    ],
  },
  pathways: {
    "p1-procrastination": {
      id: "p1-procrastination",
      title: "Maîtriser la Procrastination en 30 Jours",
      description:
        "Un programme structuré pour construire des habitudes d'action durable.",
      durationWeeks: 4,
      plan: [
        [
          {
            id: "p1w1t1",
            type: "tool",
            title: 'Comprendre votre "Pourquoi"',
            toolId: "fear-setting",
            points: 20,
          },
          {
            id: "p1w1t2",
            type: "ritual",
            title: 'Ancrer le rituel de la "Tâche Prioritaire"',
            ritual: { id: "r-tpi", text: "Définir ma TPI du jour", icon: "🎯" },
            points: 10,
          },
          {
            id: "p1w1t3",
            type: "challenge",
            title: 'Ajouter le défi "Victoire Rapide"',
            challengeId: "c-quickwin",
            points: 30,
          },
          {
            id: "p1w1t4",
            type: "focus",
            title: "Faire une session focus sur votre TPI",
            points: 15,
          },
        ],
        [
          {
            id: "p1w2t1",
            type: "tool",
            title: "Prioriser avec la Matrice d'Eisenhower",
            toolId: "eisenhower",
            points: 20,
          },
          {
            id: "p1w2t2",
            type: "focus",
            title: "Compléter 3 sessions focus cette semaine",
            points: 50,
          },
          {
            id: "p1w2t3",
            type: "journal",
            title: "Noter les moments de résistance",
            points: 15,
          },
        ],
      ],
    },
    "p2-fitness": {
      id: "p2-fitness",
      title: "Construire une Routine Sportive en 4 Semaines",
      description:
        "Passez de zéro à une routine sportive régulière que vous aimez.",
      durationWeeks: 4,
      plan: [],
    },
  },
};
